/**
 * SEND Reform Navigator - Content Sources Registry
 *
 * Single source of truth for all referenced sources across the site.
 * Every factual claim must have a traceable source listed here.
 *
 * HOW TO ADD A NEW SOURCE:
 * 1. Pick the correct `type` from AcceptedSourceType (see guardrails.ts)
 * 2. Give it a unique `id` (lowercase, hyphenated)
 * 3. Fill in name, url, description, and category
 * 4. List the page paths where the source is referenced in `usedIn`
 * 5. The Sources page auto-renders from this file — no other changes needed
 */

import { type AcceptedSourceType } from "./guardrails";

// =============================================================================
// TYPES
// =============================================================================

export interface ContentSource {
  /** Unique identifier, e.g. "cfa-2014" */
  id: string;
  /** Source type category from guardrails */
  type: AcceptedSourceType;
  /** Display name shown on the Sources page */
  name: string;
  /** Full URL to the source */
  url: string;
  /** Short description explaining what this source covers and why it matters */
  description: string;
  /** Grouping label for the Sources page (e.g. "SEND law and legal framework") */
  category: string;
  /** Page paths where this source is referenced */
  usedIn: string[];
  /** ISO date string of when the source was last accessed */
  dateAccessed?: string;
  /** ISO date string of when the source was published */
  datePublished?: string;
  /** Internal editorial notes */
  notes?: string;
}

// =============================================================================
// CATEGORY DISPLAY ORDER
// =============================================================================

export const sourceCategoryOrder: string[] = [
  "Primary legislation",
  "Statutory guidance",
  "Government policy documents and official data",
  "Parliamentary sources",
  "Regulatory and oversight bodies",
  "Legal and advice organisations",
  "Established sector and investigative media",
  "Research and analysis",
  // Legacy categories kept for existing sources not yet remapped
  "SEND law and legal framework",
  "Government announcements and programmes",
  "Official statistics",
  "Parliamentary reports and briefings",
  "Audit and fiscal bodies",
  "Local government",
  "Consultation and engagement material",
  "Ofsted and inspection information",
  "Tribunal and appeals information",
  "Education sector press",
  "Legal and sector analysis",
  "Parent-led and sector analysis",
  "Media reporting referenced",
  "Practical support and template letters",
];

// =============================================================================
// SOURCE REGISTRY
// =============================================================================

export const sourceRegistry: ContentSource[] = [
  // ── SEND law and legal framework ──────────────────────────────────────────
  {
    id: "cfa-2014",
    type: "government_primary",
    name: "Children and Families Act 2014",
    url: "https://www.legislation.gov.uk/ukpga/2014/6/contents/enacted",
    description: "The primary legislation that created EHCPs and defines parental rights in SEND.",
    category: "SEND law and legal framework",
    usedIn: ["/where-we-are-now", "/what-has-not-changed", "/ehcps", "/about"],
    datePublished: "2014-03-13",
    dateAccessed: "2026-02-04",
  },
  {
    id: "send-cop-2015",
    type: "government_primary",
    name: "SEND Code of Practice: 0 to 25 years",
    url: "https://www.gov.uk/government/publications/send-code-of-practice-0-to-25",
    description: "Statutory guidance explaining how the law works in practice — schools and LAs must follow this.",
    category: "SEND law and legal framework",
    usedIn: ["/where-we-are-now", "/what-has-not-changed", "/ehcps"],
    datePublished: "2015-01-01",
    dateAccessed: "2026-02-04",
  },

  // ── Government announcements and programmes ───────────────────────────────
  {
    id: "send-ap-improvement-plan",
    type: "government_primary",
    name: "SEND and Alternative Provision Improvement Plan",
    url: "https://www.gov.uk/government/publications/send-and-alternative-provision-improvement-plan",
    description: "The government's original 2023 plan for reforming SEND — many current changes stem from this.",
    category: "Government announcements and programmes",
    usedIn: ["/what-is-changing", "/what-we-know-so-far"],
    datePublished: "2023-03-02",
    dateAccessed: "2026-02-04",
  },
  {
    id: "send-transformational-reform",
    type: "government_primary",
    name: "Transformational reform begins for children and young people with SEND",
    url: "https://www.gov.uk/government/news/transformational-reform-begins-for-children-and-young-people-with-send",
    description: "Announcement of the £5bn council deficit bailout and central government taking over SEND spending.",
    category: "Government announcements and programmes",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "3bn-send-investment",
    type: "government_primary",
    name: "£3bn investment to end postcode lottery for children with SEND",
    url: "https://www.gov.uk/government/news/3bn-investment-to-end-postcode-lottery-for-children-with-send",
    description: "Capital investment creating 60,000 new specialist and mainstream SEND places.",
    category: "Government announcements and programmes",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "national-conversation-launch",
    type: "government_primary",
    name: "Government launches national conversation on SEND",
    url: "https://www.gov.uk/government/news/government-launches-national-conversation-on-send",
    description: "Launch of the public consultation that ran Dec 2025 to Jan 2026 — parents could respond directly.",
    category: "Government announcements and programmes",
    usedIn: ["/what-is-changing", "/what-is-being-discussed"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "200m-send-training",
    type: "government_primary",
    name: "£200 million landmark SEND teacher training programme",
    url: "https://www.gov.uk/government/news/200-million-landmark-send-teacher-training-programme",
    description: "Confirmed funding for mandatory SEND training for all teachers and expanded SENCO routes.",
    category: "Government announcements and programmes",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "10-year-schools-plan",
    type: "government_primary",
    name: "10 Year Plan to Revitalise Schools and Colleges for Every Child",
    url: "https://www.gov.uk/government/publications/10-year-plan-to-revitalise-schools-and-colleges",
    description: "Wider schools strategy — includes inclusion bases, Ofsted reforms, and SEND capital plans.",
    category: "Government announcements and programmes",
    usedIn: ["/what-is-changing", "/what-we-know-so-far"],
    datePublished: "2026-02-10",
    dateAccessed: "2026-02-15",
  },
  {
    id: "dfe-fe-update",
    type: "government_primary",
    name: "DfE Update to the Further Education Sector (February 2026)",
    url: "https://www.gov.uk/government/publications/dfe-update-further-education-sector",
    description: "Guidance on how SEND changes affect post-16 colleges and further education settings.",
    category: "Government announcements and programmes",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "kcsie-hansard",
    type: "parliamentary",
    name: "Keeping Children Safe in Education consultation statement (Hansard, 12 Feb 2026)",
    url: "https://hansard.parliament.uk/",
    description: "Ministerial statement on safeguarding guidance — relevant to SEND children in all settings.",
    category: "Government announcements and programmes",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },

  // ── Official statistics ───────────────────────────────────────────────────
  {
    id: "sen-statistics",
    type: "government_primary",
    name: "Special educational needs in England statistics",
    url: "https://explore-education-statistics.service.gov.uk/find-statistics/special-educational-needs-in-england",
    description: "Official data on how many children have SEND, what type, and where they are educated.",
    category: "Official statistics",
    usedIn: ["/where-we-are-now", "/what-we-know-so-far"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "ehcp-data-tables",
    type: "government_primary",
    name: "Education, Health and Care Plan data tables",
    url: "https://explore-education-statistics.service.gov.uk/find-statistics/education-health-and-care-plans",
    description: "Detailed breakdowns of EHCP numbers, timeliness, refusal rates, and trends over time.",
    category: "Official statistics",
    usedIn: ["/where-we-are-now", "/ehcps", "/what-we-know-so-far"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "tribunals-stats",
    type: "government_primary",
    name: "Tribunals statistics quarterly",
    url: "https://www.gov.uk/government/statistics/tribunals-statistics-quarterly",
    description: "How many SEND tribunal appeals are filed, how long they take, and what outcomes parents get.",
    category: "Official statistics",
    usedIn: ["/where-we-are-now", "/ehcps"],
    dateAccessed: "2026-02-15",
  },

  // ── Parliamentary reports and briefings ────────────────────────────────────
  {
    id: "commons-library-send",
    type: "parliamentary",
    name: "House of Commons Library briefing on SEND",
    url: "https://researchbriefings.files.parliament.uk/documents/SN07020/SN07020.pdf",
    description: "Comprehensive background briefing used by MPs — covers law, statistics, and policy context.",
    category: "Parliamentary reports and briefings",
    usedIn: ["/what-we-know-so-far"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "pac-send-report",
    type: "parliamentary",
    name: "Public Accounts Committee report on SEND",
    url: "https://publications.parliament.uk/pa/cm5901/cmselect/cmpubacc/353/report.html",
    description: "Investigation into whether SEND spending delivers value for money — found it does not.",
    category: "Parliamentary reports and briefings",
    usedIn: ["/what-we-know-so-far", "/where-we-are-now"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "edcom-send-report",
    type: "parliamentary",
    name: "Education Committee report on SEND",
    url: "https://publications.parliament.uk/pa/cm5901/cmselect/cmeduc/492/report.html",
    description: "Cross-party examination of how SEND reform should be designed to protect children's rights.",
    category: "Parliamentary reports and briefings",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "lords-send-debate",
    type: "parliamentary",
    name: "House of Lords debate on SEND budget funding",
    url: "https://hansard.parliament.uk/Lords/2025-12-03/debates/46811928-0773-4D27-984F-5802CBBF5824/SENDBudgetFunding",
    description: "Lords raised concerns about council insolvency and the impact of deficits on SEND provision.",
    category: "Parliamentary reports and briefings",
    usedIn: ["/what-we-know-so-far"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "edcom-committee",
    type: "parliamentary",
    name: "House of Commons Education Committee",
    url: "https://committees.parliament.uk/committee/203/education-committee/",
    description: "The committee actively scrutinising SEND reform proposals — publishes evidence and recommendations.",
    category: "Parliamentary reports and briefings",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "health-ed-mh-inquiry",
    type: "parliamentary",
    name: "Health and Social Care and Education Committees inquiry into children and young people's mental health (13 Feb 2026)",
    url: "https://committees.parliament.uk/",
    description: "New joint inquiry examining how education and health services support children's mental health, including SEND.",
    category: "Parliamentary reports and briefings",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "commons-library-briefing",
    type: "parliamentary",
    name: "Commons Library briefing on SEND in England",
    url: "https://commonslibrary.parliament.uk/research-briefings/sn07020/",
    description: "Regularly updated research briefing — good single-page summary of the current SEND landscape.",
    category: "Parliamentary reports and briefings",
    usedIn: ["/what-we-know-so-far"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "westminster-hall-send",
    type: "parliamentary",
    name: "Westminster Hall debates on SEND and EHCPs",
    url: "https://hansard.parliament.uk/",
    description: "MPs sharing constituent experiences and pressing ministers on EHCP delays and funding.",
    category: "Parliamentary reports and briefings",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-15",
  },

  // ── Audit and fiscal bodies ───────────────────────────────────────────────
  {
    id: "nao-send-report",
    type: "public_body",
    name: "NAO report on support for children with special educational needs",
    url: "https://www.nao.org.uk/reports/support-for-children-and-young-people-with-special-educational-needs",
    description: "Found the SEND system is 'not delivering value for money' — key evidence behind reform calls.",
    category: "Audit and fiscal bodies",
    usedIn: ["/where-we-are-now", "/what-we-know-so-far"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "nao-send-sustainability",
    type: "public_body",
    name: "NAO press release on SEND system financial sustainability",
    url: "https://www.nao.org.uk/press-releases/special-educational-needs-system-is-financially-unsustainable",
    description: "Warned that without intervention, most councils would face insolvency from SEND debts alone.",
    category: "Audit and fiscal bodies",
    usedIn: ["/where-we-are-now"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "ifs-send-spending",
    type: "public_body",
    name: "IFS analysis on SEND and childcare spending",
    url: "https://ifs.org.uk/news/rapid-rises-send-and-childcare-spending-are-reshaping-education-spending-england",
    description: "Shows how rising SEND costs are crowding out mainstream education spending across England.",
    category: "Audit and fiscal bodies",
    usedIn: ["/where-we-are-now", "/what-we-know-so-far"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "pac-findings",
    type: "parliamentary",
    name: "Public Accounts Committee findings on SEND",
    url: "https://committees.parliament.uk/committee/127/public-accounts-committee/",
    description: "Parliamentary scrutiny of how taxpayer money is being spent on SEND — highlights waste and delay.",
    category: "Audit and fiscal bodies",
    usedIn: ["/what-we-know-so-far"],
    dateAccessed: "2026-02-15",
  },

  // ── Local government ──────────────────────────────────────────────────────
  {
    id: "lga-send-reform",
    type: "sector_briefing",
    name: "LGA briefing on SEND reform",
    url: "https://www.local.gov.uk/parliament/briefings-and-responses/special-educational-needs-and-disabilities-send-reform",
    description: "How councils are preparing for reform and what they say they need from central government.",
    category: "Local government",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "lga-dsg-debate",
    type: "sector_briefing",
    name: "LGA briefing on Westminster Hall debate on DSG",
    url: "https://www.local.gov.uk/parliament/briefings-and-responses/westminster-hall-debate-dedicated-schools-grant-23-april-2025",
    description: "Council perspective on the Dedicated Schools Grant and why SEND deficits keep growing.",
    category: "Local government",
    usedIn: ["/where-we-are-now"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "lga-send-reports",
    type: "sector_briefing",
    name: "LGA SEND reports and briefings",
    url: "https://www.local.gov.uk/topics/education-and-schools/send",
    description: "Ongoing council analysis of SEND provision, workforce, and financial pressures.",
    category: "Local government",
    usedIn: ["/where-we-are-now", "/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "lga-send-deficits-feb26",
    type: "sector_briefing",
    name: "LGA: SEND deficits and insolvency risk for councils (February 2026)",
    url: "https://www.local.gov.uk/topics/education-and-schools/send",
    description: "Latest council data showing 43% forecast deficits equal to or exceeding their reserves.",
    category: "Local government",
    usedIn: ["/where-we-are-now"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "ccn-deficit-coverage",
    type: "sector_briefing",
    name: "County Councils Network: Government commits to covering 90% of SEND deficits (12 Feb 2026)",
    url: "https://www.countycouncilsnetwork.org.uk/",
    description: "Confirmation that central government will absorb the majority of accumulated council SEND debt.",
    category: "Local government",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },

  // ── Consultation and engagement material ──────────────────────────────────
  {
    id: "send-national-conversation",
    type: "government_primary",
    name: "SEND Reform National Conversation",
    url: "https://consult.education.gov.uk/digital-communication-team/send-reform-national-conversation",
    description: "The official consultation where parents, schools, and professionals could submit views on reform.",
    category: "Consultation and engagement material",
    usedIn: ["/what-is-being-discussed", "/what-is-changing"],
    dateAccessed: "2026-02-04",
  },

  // ── Ofsted and inspection information ─────────────────────────────────────
  {
    id: "ofsted-area-send",
    type: "public_body",
    name: "Ofsted and CQC area SEND inspections",
    url: "https://www.gov.uk/government/collections/local-area-send-inspections",
    description: "Reports on how well each local area supports children with SEND — your area may have one.",
    category: "Ofsted and inspection information",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "ofsted-inclusion",
    type: "public_body",
    name: "Ofsted reports on inclusion and SEND",
    url: "https://www.gov.uk/government/organisations/ofsted",
    description: "Inspection findings on how schools are including and supporting children with SEND.",
    category: "Ofsted and inspection information",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },

  // ── Tribunal and appeals information ──────────────────────────────────────
  {
    id: "send-tribunal-guidance",
    type: "government_primary",
    name: "SEND Tribunal guidance",
    url: "https://www.gov.uk/courts-tribunals/first-tier-tribunal-special-educational-needs-and-disability",
    description: "How to appeal an EHCP decision — process, timescales, what to expect, and how to prepare.",
    category: "Tribunal and appeals information",
    usedIn: ["/ehcps", "/what-has-not-changed"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "moj-tribunal-stats",
    type: "government_primary",
    name: "Ministry of Justice tribunal statistics",
    url: "https://www.gov.uk/government/collections/tribunals-statistics",
    description: "Official data on appeal volumes, wait times, and outcomes — parents win around 95% of decided cases.",
    category: "Tribunal and appeals information",
    usedIn: ["/ehcps", "/where-we-are-now"],
    dateAccessed: "2026-02-15",
  },

  // ── Education sector press ────────────────────────────────────────────────
  {
    id: "schools-week-reform-planning",
    type: "established_media",
    name: "Schools Week: DfE orders councils to begin SEND reform planning (6 Feb 2026)",
    url: "https://schoolsweek.co.uk/",
    description: "Councils told to submit local reform plans by autumn 2026 to qualify for deficit bailout funding.",
    category: "Education sector press",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "schools-week-inclusion-bases",
    type: "established_media",
    name: "Schools Week: DfE expects all secondary schools to have inclusion bases (11 Feb 2026)",
    url: "https://schoolsweek.co.uk/",
    description: "Government expectation that every secondary will have dedicated space for SEND support.",
    category: "Education sector press",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "tes-ks4-send",
    type: "established_media",
    name: "TES: Nearly a fifth of KS4 pupils now recorded with SEND (10 Feb 2026)",
    url: "https://www.tes.com/",
    description: "Shows the scale of SEND identification — one in five Year 10 and 11 pupils now have identified needs.",
    category: "Education sector press",
    usedIn: ["/where-we-are-now"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "tes-estates-inclusion",
    type: "established_media",
    name: "TES: DfE estates strategy signals inclusion bases in every secondary (11 Feb 2026)",
    url: "https://www.tes.com/",
    description: "Details on the building and estates plans behind the inclusion base rollout.",
    category: "Education sector press",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "unherd-send-children",
    type: "established_media",
    name: "UnHerd: Who will defend SEND children (February 2026)",
    url: "https://unherd.com/",
    description: "Opinion piece questioning whether reform will protect or weaken children's rights.",
    category: "Education sector press",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-15",
  },

  // ── Legal and sector analysis ─────────────────────────────────────────────
  {
    id: "farrer-sen-reforms",
    type: "sector_briefing",
    name: "Farrer and Co on proposed reforms to SEN support",
    url: "https://www.farrer.co.uk/news-and-insights/proposed-reforms-to-sen-support-in-england-what-schools-need-to-know",
    description: "Law firm analysis of what reforms mean for schools and how duties might change.",
    category: "Legal and sector analysis",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "lexology-send",
    type: "sector_briefing",
    name: "Lexology SEND legal analysis",
    url: "https://www.lexology.com/library/detail.aspx?g=de0f0d8c-a678-47b3-8d25-e448f90a7d2e",
    description: "Legal commentary on proposed SEND changes and their implications for rights and enforcement.",
    category: "Legal and sector analysis",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "russell-cooke-send",
    type: "sector_briefing",
    name: "Russell Cooke SEND law briefings",
    url: "https://www.russell-cooke.co.uk/insights/send/",
    description: "Specialist SEND solicitors explaining legal developments in plain language for parents.",
    category: "Legal and sector analysis",
    usedIn: ["/what-has-not-changed"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "farrer-send-updates",
    type: "sector_briefing",
    name: "Farrer and Co SEND legal updates",
    url: "https://www.farrer.co.uk/insights/schools/",
    description: "Ongoing legal updates on SEND policy, case law, and what schools need to know.",
    category: "Legal and sector analysis",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-15",
  },

  // ── Parent-led and sector analysis ────────────────────────────────────────
  {
    id: "snj",
    type: "sector_briefing",
    name: "Special Needs Jungle",
    url: "https://www.specialneedsjungle.com/",
    description: "Independent parent-led site — detailed analysis of SEND policy, rights, and reform proposals.",
    category: "Parent-led and sector analysis",
    usedIn: ["/what-is-being-discussed", "/what-the-leaks-are-saying"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "contact-charity",
    type: "sector_briefing",
    name: "Contact charity SEND policy and analysis",
    url: "https://contact.org.uk/",
    description: "National charity providing practical SEND guidance, helplines, and policy briefings for families.",
    category: "Parent-led and sector analysis",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "contact-inclusion-bases",
    type: "sector_briefing",
    name: "Contact: Inclusion bases in mainstream secondary schools explained (Feb 2026)",
    url: "https://contact.org.uk/",
    description: "What inclusion bases are, how they work, and what they mean for children currently in specialist provision.",
    category: "Parent-led and sector analysis",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "contact-ehcp-deadlines",
    type: "sector_briefing",
    name: "Contact: EHCP transition deadline reminders for parents (Feb 2026)",
    url: "https://contact.org.uk/",
    description: "Key dates and deadlines parents need to know for EHCP annual reviews and phase transfers.",
    category: "Parent-led and sector analysis",
    usedIn: ["/ehcps"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "druk",
    type: "sector_briefing",
    name: "Disability Rights UK policy briefings",
    url: "https://www.disabilityrightsuk.org/",
    description: "Rights-based analysis of SEND reform from a disability equality perspective.",
    category: "Parent-led and sector analysis",
    usedIn: ["/what-is-being-discussed"],
    dateAccessed: "2026-02-04",
  },

  // ── Media reporting referenced ────────────────────────────────────────────
  {
    id: "guardian-campaign-send-rights",
    type: "established_media",
    name: "The Guardian: Campaign urges Starmer not to diminish SEND rights",
    url: "https://www.theguardian.com/education/2026/jan/12/new-campaign-urges-starmer-not-to-diminish-legal-rights-of-send-children",
    description: "Coverage of the Save Our Children's Rights campaign and its 130,000+ petition signatures.",
    category: "Media reporting referenced",
    usedIn: ["/what-the-leaks-are-saying", "/what-is-being-discussed"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "guardian-parents-fear",
    type: "established_media",
    name: "The Guardian: Parents fear losing support due to SEND reforms",
    url: "https://www.theguardian.com/education/2026/jan/29/parents-in-england-fear-losing-support-for-disabled-children-due-to-special-needs-reforms-send",
    description: "Parent voices on anxiety about whether reforms will reduce access to support.",
    category: "Media reporting referenced",
    usedIn: ["/what-the-leaks-are-saying"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "guardian-disabled-children-rights",
    type: "established_media",
    name: "The Guardian: Disabled children legal rights and SEND ministers",
    url: "https://www.theguardian.com/education/2026/feb/02/disabled-children-legal-rights-send-ministers-special-needs-education-england",
    description: "Reporting on ministerial statements about maintaining legal protections during reform.",
    category: "Media reporting referenced",
    usedIn: ["/what-has-not-changed"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "guardian-labour-rebellion",
    type: "established_media",
    name: "The Guardian: Ministers lobbying blitz to avoid Labour rebellion",
    url: "https://www.theguardian.com/politics/2026/feb/01/ministers-lobbying-blitz-avoid-labour-rebellion-send-changes",
    description: "Internal Labour pushback against reforms seen as weakening children's rights.",
    category: "Media reporting referenced",
    usedIn: ["/what-the-leaks-are-saying"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "guardian-autistic-absence",
    type: "established_media",
    name: "The Guardian: One in six autistic pupils have not attended school",
    url: "https://www.theguardian.com/education/2026/feb/04/one-in-six-autistic-pupils-in-uk-have-not-attended-school-at-all-since-september",
    description: "Investigation into school absence among autistic children — one in six not attending at all.",
    category: "Media reporting referenced",
    usedIn: ["/where-we-are-now"],
    dateAccessed: "2026-02-04",
  },
  {
    id: "guardian-keep-support",
    type: "established_media",
    name: "The Guardian: Children with special needs will keep current support (9 Feb 2026)",
    url: "https://www.theguardian.com/education/2026/feb/09/children-special-needs-keep-current-support",
    description: "Minister Georgia Gould confirms existing EHCPs and placements will be protected during reform.",
    category: "Media reporting referenced",
    usedIn: ["/what-has-not-changed"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "guardian-deprived-areas",
    type: "established_media",
    name: "The Guardian: SEND provision leaving deprived areas behind (11 Feb 2026)",
    url: "https://www.theguardian.com/education/2026/feb/11/send-provision-deprived-areas",
    description: "Evidence that SEND support quality varies by deprivation — poorer areas get worse outcomes.",
    category: "Media reporting referenced",
    usedIn: ["/where-we-are-now"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "guardian-treasury-pressure",
    type: "established_media",
    name: "The Guardian: Treasury pressure over £6bn SEND costs (13 Feb 2026)",
    url: "https://www.theguardian.com/education/2026/feb/13/treasury-pressure-send-costs",
    description: "Treasury pushing for cost control on SEND — raises concerns about financial pressure shaping reform.",
    category: "Media reporting referenced",
    usedIn: ["/what-the-leaks-are-saying"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "guardian-send-coverage",
    type: "established_media",
    name: "The Guardian education and SEND reporting",
    url: "https://www.theguardian.com/education/send",
    description: "Ongoing Guardian coverage of SEND policy, parent stories, and reform developments.",
    category: "Media reporting referenced",
    usedIn: ["/what-the-leaks-are-saying"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "times-school-changes",
    type: "established_media",
    name: "The Times: Schools to get list of changes for special needs (14 Feb 2026)",
    url: "https://www.thetimes.com/education",
    description: "Report that schools will receive specific guidance on what SEND changes they need to prepare for.",
    category: "Media reporting referenced",
    usedIn: ["/what-is-changing"],
    dateAccessed: "2026-02-15",
  },
  {
    id: "ft-send-reform",
    type: "established_media",
    name: "Financial Times reporting on SEND reform",
    url: "https://www.ft.com/education",
    description: "FT coverage focusing on the financial and economic dimensions of SEND reform.",
    category: "Media reporting referenced",
    usedIn: ["/what-the-leaks-are-saying"],
    dateAccessed: "2026-02-15",
  },

  // ── Practical support and template letters ─────────────────────────────────
  {
    id: "ipsea-model-letter-6",
    type: "sector_briefing",
    name: "IPSEA Model Letter 6: provision not being made",
    url: "https://www.ipsea.org.uk/complaining-when-the-provision-in-an-ehc-plan-is-not-being-made-model-letter-6",
    description: "Template letter for formally complaining when EHCP provision is not being delivered.",
    category: "Practical support and template letters",
    usedIn: ["/what-to-do-right-now"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "ipsea-model-letter-10",
    type: "sector_briefing",
    name: "IPSEA Model Letter 10: LA delays on draft/final plan",
    url: "https://www.ipsea.org.uk/complaining-when-a-local-authority-does-not-send-a-draft-or-final-education-health-and-care-plan-on-time-model-letter-10",
    description: "Template letter for when a local authority misses statutory timescales for issuing an EHCP.",
    category: "Practical support and template letters",
    usedIn: ["/what-to-do-right-now"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "gov-uk-appeal-ehcp",
    type: "government_primary",
    name: "GOV.UK — How to appeal an EHCP decision",
    url: "https://www.gov.uk/appeal-ehc-plan-decision",
    description: "Official guidance on the process for appealing EHCP decisions to the SEND Tribunal.",
    category: "Practical support and template letters",
    usedIn: ["/what-to-do-right-now"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "lgsco-send-fact-sheet",
    type: "public_body",
    name: "LGSCO SEND fact sheet",
    url: "https://www.lgo.org.uk/make-a-complaint/fact-sheets/education/special-educational-needs",
    description: "Complaints guidance from the Local Government and Social Care Ombudsman for SEND issues.",
    category: "Practical support and template letters",
    usedIn: ["/what-to-do-right-now"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "find-local-sendiass",
    type: "public_body",
    name: "Find your local SENDIASS",
    url: "https://councilfordisabledchildren.org.uk/iassnetwork/find-your-local-iass",
    description: "Service finder for free, impartial SEND Information, Advice and Support Services in every local authority.",
    category: "Practical support and template letters",
    usedIn: ["/what-to-do-right-now"],
    dateAccessed: "2026-02-19",
  },

  // ── Post-16 and transition sources ─────────────────────────────────────────
  {
    id: "ipsea-cease-to-maintain",
    type: "sector_briefing",
    name: "IPSEA: cease to maintain decisions",
    url: "https://www.ipsea.org.uk/appeals-against-decisions-to-cease-to-maintain-an-ehc-plan",
    description: "Guidance on appealing a local authority decision to cease an EHCP, including post-16.",
    category: "Practical support and template letters",
    usedIn: ["/post-16-and-transition"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "access-to-work",
    type: "government_primary",
    name: "Access to Work — GOV.UK",
    url: "https://www.gov.uk/access-to-work",
    description: "DWP funding scheme for workplace support, specialist equipment, and travel — available from age 16.",
    category: "Practical support and template letters",
    usedIn: ["/post-16-and-transition"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "druk-care-act-guide",
    type: "sector_briefing",
    name: "Disability Rights UK: Care Act guide",
    url: "https://www.disabilityrightsuk.org/how-we-can-help/benefits-information/factsheets/adult-social-care",
    description: "Practical guide to adult social care assessments and entitlements under the Care Act 2014.",
    category: "Practical support and template letters",
    usedIn: ["/post-16-and-transition"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "snj-cease-maintain-post16",
    type: "sector_briefing",
    name: "Special Needs Jungle: ceasing to maintain an EHCP post-16",
    url: "https://www.specialneedsjungle.com/ceasing-maintain-ehc-plan/",
    description: "Analysis of LA practices around ending EHCPs at post-16 and how to challenge them.",
    category: "Parent-led and sector analysis",
    usedIn: ["/post-16-and-transition"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "equality-act-2010",
    type: "government_primary",
    name: "Equality Act 2010",
    url: "https://www.legislation.gov.uk/ukpga/2010/15/contents",
    description: "Establishes the protected characteristic of disability and duties on schools not to discriminate.",
    category: "SEND law and legal framework",
    usedIn: ["/post-16-and-transition", "/what-has-not-changed"],
    datePublished: "2010-04-08",
    dateAccessed: "2026-02-19",
  },
  {
    id: "care-act-2014",
    type: "government_primary",
    name: "Care Act 2014",
    url: "https://www.legislation.gov.uk/ukpga/2014/23/contents/enacted",
    description: "Governs adult social care — relevant to transition from children's to adult services at 18.",
    category: "SEND law and legal framework",
    usedIn: ["/post-16-and-transition"],
    datePublished: "2014-05-14",
    dateAccessed: "2026-02-19",
  },

  // ── SENDIASS sources ───────────────────────────────────────────────────────
  {
    id: "iass-network",
    type: "public_body",
    name: "IASS Network — national body for SENDIASS services",
    url: "https://iassnetwork.org.uk",
    description: "The national network supporting local SENDIASS services across England.",
    category: "Practical support and template letters",
    usedIn: ["/sendiass"],
    dateAccessed: "2026-02-19",
  },

  // ── Consultation and participation sources ─────────────────────────────────
  {
    id: "uk-parliament-petitions",
    type: "parliamentary",
    name: "UK Parliament petitions",
    url: "https://petition.parliament.uk",
    description: "Start or sign a parliamentary petition — 10,000 signatures triggers a government response, 100,000 triggers a debate.",
    category: "Consultation and engagement material",
    usedIn: ["/have-your-say"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "writetothem",
    type: "sector_briefing",
    name: "WriteToThem — contact your MP",
    url: "https://www.writetothem.com",
    description: "Find and write to your MP directly about SEND issues in your local area.",
    category: "Consultation and engagement material",
    usedIn: ["/have-your-say"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "appg-send",
    type: "parliamentary",
    name: "SEND All-Party Parliamentary Group",
    url: "https://appg-send.org.uk",
    description: "Cross-party group of MPs and peers focused on SEND — publishes reports and signals parliamentary direction.",
    category: "Parliamentary reports and briefings",
    usedIn: ["/have-your-say"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "contact-white-paper",
    type: "sector_briefing",
    name: "Contact: what happens after the White Paper",
    url: "https://contact.org.uk/about-contact/news-and-views/send-reforms-white-paper-what-happens-next/",
    description: "Analysis of what families should expect once the White Paper is published.",
    category: "Parent-led and sector analysis",
    usedIn: ["/have-your-say"],
    dateAccessed: "2026-02-19",
  },

  // ── Reality Bites series sources ──────────────────────────────────────────
  {
    id: "smartphone-free-dopamine",
    type: "sector_briefing",
    name: "The Day We Gave Children Dopamine on Demand",
    url: "https://smartphonefree.neurodiversityglobal.com/",
    description: "Rich Ferriman's analysis of neurodivergence, screens, and what families can do about dopamine-driven behaviour.",
    category: "Parent-led and sector analysis",
    usedIn: ["/what-we-owe-our-children"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "awbp-open-letter",
    type: "sector_briefing",
    name: "Are We Bad Parents? — An Open Letter",
    url: "https://awbp.neuro.support/",
    description: "Rich Ferriman's open letter to neurodivergent families — honest, direct, and grounded in lived experience.",
    category: "Parent-led and sector analysis",
    usedIn: ["/what-we-owe-our-children"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "pda-society",
    type: "sector_briefing",
    name: "PDA Society — guidance for families and schools",
    url: "https://www.pdasociety.org.uk",
    description: "Specialist guidance on Pathological Demand Avoidance profiles, strategies, and school support.",
    category: "Legal and advice organisations",
    usedIn: ["/what-we-owe-our-children"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "nnpcf",
    type: "sector_briefing",
    name: "NNPCF — National Network of Parent Carer Forums",
    url: "https://nnpcf.org.uk",
    description: "Searchable directory of local parent carer forums across England, with formal role in local SEND systems.",
    category: "Legal and advice organisations",
    usedIn: ["/for-parents"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "contact-charity",
    type: "sector_briefing",
    name: "Contact — for families with disabled children",
    url: "https://contact.org.uk",
    description: "National charity providing helpline, practical guides, and parent-to-parent support for families with disabled children.",
    category: "Legal and advice organisations",
    usedIn: ["/for-parents"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "carers-uk",
    type: "sector_briefing",
    name: "Carers UK",
    url: "https://www.carersuk.org",
    description: "Carer rights, financial guidance, mental health support, and carer's assessment information.",
    category: "Legal and advice organisations",
    usedIn: ["/for-parents"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "scope",
    type: "sector_briefing",
    name: "Scope",
    url: "https://www.scope.org.uk",
    description: "Online community and helpline with specific support for parents of disabled children.",
    category: "Legal and advice organisations",
    usedIn: ["/for-parents"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "samaritans",
    type: "sector_briefing",
    name: "Samaritans",
    url: "https://www.samaritans.org",
    description: "Free 24-hour listening service available to anyone who needs to talk — not crisis-only.",
    category: "Legal and advice organisations",
    usedIn: ["/for-parents"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "dfe-exclusion-guidance-2023",
    type: "government_primary",
    name: "DfE Suspension and Permanent Exclusion guidance (2023)",
    url: "https://www.gov.uk/government/publications/school-exclusion",
    description: "Statutory guidance on school exclusion procedures, governing body duties, and Independent Review Panels.",
    category: "Statutory guidance and frameworks",
    usedIn: ["/exclusions"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "dfe-exclusions-stats-2024-25",
    type: "government_primary",
    name: "DfE exclusions statistics autumn 2024/25",
    url: "https://explore-education-statistics.service.gov.uk/find-statistics/suspensions-and-permanent-exclusions-in-england/2024-25-autumn-term",
    description: "Official statistics on suspension and permanent exclusion rates by SEN status, published November 2025.",
    category: "Government policy and operational documents",
    usedIn: ["/exclusions"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "ipsea-exclusions",
    type: "sector_briefing",
    name: "IPSEA exclusions guidance",
    url: "https://www.ipsea.org.uk/exclusions",
    description: "Free independent legally-based advice on school exclusions for families of children with SEND.",
    category: "Legal and advice organisations",
    usedIn: ["/exclusions"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "sossen",
    type: "sector_briefing",
    name: "SOS!SEN",
    url: "https://sossen.org.uk",
    description: "Free helpline and independent advice for parents of children with special educational needs.",
    category: "Legal and advice organisations",
    usedIn: ["/exclusions"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "commons-library-exclusions-2025",
    type: "parliamentary",
    name: "House of Commons Library — School Exclusions briefing (Sept 2025)",
    url: "https://commonslibrary.parliament.uk/research-briefings/cbp-10343/",
    description: "Parliamentary research briefing covering exclusion trends, disproportionality, and SEND overlap.",
    category: "Parliamentary and legislative sources",
    usedIn: ["/exclusions"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "cfa-2014-section-42",
    type: "government_primary",
    name: "Children and Families Act 2014, Section 42",
    url: "https://www.legislation.gov.uk/ukpga/2014/6/section/42",
    description: "Primary legislation establishing the legal duty on health commissioning bodies to provide health care provision specified in Section G of an EHC plan.",
    category: "Primary legislation and case law",
    usedIn: ["/ehcp-health"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "send-regulations-2014",
    type: "government_primary",
    name: "SEND Regulations 2014",
    url: "https://www.legislation.gov.uk/uksi/2014/1530/contents/made",
    description: "Secondary legislation governing the EHC needs assessment process, timescales, and rights to request amendments.",
    category: "Primary legislation and case law",
    usedIn: ["/ehcp-health"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "nhs-find-icb",
    type: "sector_briefing",
    name: "NHS — find your local ICB",
    url: "https://www.nhs.uk/nhs-services/find-your-local-integrated-care-board/",
    description: "Service finder for locating your local Integrated Care Board, responsible for NHS commissioning including EHC plan health provision.",
    category: "Government policy and operational documents",
    usedIn: ["/ehcp-health"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "young-minds",
    type: "sector_briefing",
    name: "Young Minds",
    url: "https://www.youngminds.org.uk",
    description: "Mental health support and guidance for young people and parents, including resources on navigating CAMHS referrals.",
    category: "Research, analysis and sector expertise",
    usedIn: ["/ehcp-health"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "anna-freud-centre",
    type: "sector_briefing",
    name: "Anna Freud Centre",
    url: "https://www.annafreud.org",
    description: "Mental health resources for families, including guidance on children's emotional wellbeing and accessing services.",
    category: "Research, analysis and sector expertise",
    usedIn: ["/ehcp-health"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "nhs-complaints",
    type: "sector_briefing",
    name: "NHS Complaints procedure",
    url: "https://www.nhs.uk/using-the-nhs/about-the-nhs/how-to-complain-about-nhs-services/",
    description: "Official guidance on how to make a complaint about NHS services, including escalation to the Parliamentary and Health Service Ombudsman.",
    category: "Government policy and operational documents",
    usedIn: ["/ehcp-health"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "dfe-ap-statutory-guidance",
    type: "government_primary",
    name: "DfE Alternative Provision statutory guidance",
    url: "https://www.gov.uk/government/publications/alternative-provision",
    description: "Statutory guidance on the use of alternative provision, including off-site direction, quality requirements, and local authority duties.",
    category: "Statutory guidance and frameworks",
    usedIn: ["/alternative-provision"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "dfe-pupils-characteristics-2024-25",
    type: "government_primary",
    name: "DfE schools and pupils characteristics 2024/25",
    url: "https://explore-education-statistics.service.gov.uk/find-statistics/school-pupils-and-their-characteristics/2024-25",
    description: "Official statistics on school and AP pupil demographics, SEN status, and free school meals eligibility.",
    category: "Government policy and operational documents",
    usedIn: ["/alternative-provision"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "send-ap-improvement-plan",
    type: "government_primary",
    name: "SEND and AP Improvement Plan",
    url: "https://www.gov.uk/government/publications/send-and-alternative-provision-improvement-plan",
    description: "Government policy document setting out proposals for reform of SEND and Alternative Provision, including the three-tier AP model.",
    category: "Government policy and operational documents",
    usedIn: ["/alternative-provision", "/state-of-send-2026"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "ofsted-area-send-outcomes-dec-2024",
    type: "government_primary",
    name: "Ofsted Area SEND inspection outcomes, December 2024",
    url: "https://www.gov.uk/government/statistics/area-send-inspections-and-outcomes-in-england-as-at-31-december-2024",
    description: "Official statistics on area SEND inspection outcomes across 54 inspections between January 2023 and December 2024.",
    category: "Regulatory and inspection bodies",
    usedIn: ["/local-variation"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "ofsted-area-send-reports-search",
    type: "government_primary",
    name: "Ofsted local area SEND inspection reports",
    url: "https://reports.ofsted.gov.uk/search?q=&level_1_types=10",
    description: "Searchable database of individual area SEND inspection reports published by Ofsted.",
    category: "Regulatory and inspection bodies",
    usedIn: ["/local-variation"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "dfe-safety-valve-guidance",
    type: "government_primary",
    name: "DfE Dedicated Schools Grant very high deficit intervention (Safety Valve)",
    url: "https://www.gov.uk/government/publications/dedicated-schools-grant-very-high-deficit-intervention",
    description: "Policy guidance on Safety Valve agreements between the DfE and local authorities with very high SEND deficits.",
    category: "Government policy and operational documents",
    usedIn: ["/local-variation"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "ifs-send-spending-dec-2025",
    type: "sector_briefing",
    name: "IFS: Spending on SEND in England (December 2025)",
    url: "https://ifs.org.uk/publications/spending-special-educational-needs-england-something-has-change",
    description: "Institute for Fiscal Studies analysis of SEND spending trends, accumulated deficits, and the impact of the November 2025 Budget announcement.",
    category: "Research, analysis and sector expertise",
    usedIn: ["/local-variation"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "ifg-send-deficits-dec-2025",
    type: "sector_briefing",
    name: "IfG: Central government's takeover of SEND deficits (December 2025)",
    url: "https://www.instituteforgovernment.org.uk/comment/central-governments-send-deficits-reform",
    description: "Institute for Government analysis of the structural shift in SEND deficit responsibility following the November 2025 Budget.",
    category: "Research, analysis and sector expertise",
    usedIn: ["/local-variation"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "welsh-gov-aln",
    type: "government_primary",
    name: "Welsh Government ALN information for parents",
    url: "https://www.gov.wales/additional-learning-needs",
    description: "Official guidance on the Additional Learning Needs system in Wales, including parent factsheets and statutory guidance.",
    category: "Government policy and operational documents",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "snap-cymru",
    type: "public_body",
    name: "SNAP Cymru",
    url: "https://www.snapcymru.org",
    description: "Independent advice and advocacy service for families in Wales navigating the ALN system.",
    category: "Legal, advice and advocacy organisations",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "education-tribunal-wales",
    type: "government_primary",
    name: "Education Tribunal for Wales",
    url: "https://educationtribunal.gov.wales",
    description: "Handles appeals about Individual Development Plans and placements in Wales.",
    category: "Regulatory and inspection bodies",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "childrens-legal-centre-wales",
    type: "public_body",
    name: "Children's Legal Centre Wales",
    url: "https://childrenslegalcentre.wales",
    description: "Legal support and strategic litigation for children's rights in Wales.",
    category: "Legal, advice and advocacy organisations",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "scottish-gov-asl",
    type: "government_primary",
    name: "Scottish Government — additional support for learning",
    url: "https://www.gov.scot/policies/schools/additional-support-for-learning",
    description: "Official Scottish Government policy and guidance on additional support for learning.",
    category: "Government policy and operational documents",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "enquire-scotland",
    type: "public_body",
    name: "Enquire Scotland",
    url: "https://enquire.org.uk",
    description: "Scottish advice service for additional support for learning, funded by the Scottish Government.",
    category: "Legal, advice and advocacy organisations",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "lets-talk-asn",
    type: "public_body",
    name: "Let's Talk ASN",
    url: "https://www.ltasn.scot",
    description: "National advocacy and legal representation for parents and young people in relation to the Additional Support Needs Tribunal in Scotland.",
    category: "Legal, advice and advocacy organisations",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "ea-ni-sen",
    type: "government_primary",
    name: "Education Authority Northern Ireland — SEN",
    url: "https://www.eani.org.uk/parents/special-educational-needs-sen",
    description: "Official information on the statutory assessment process and SEN provision in Northern Ireland.",
    category: "Government policy and operational documents",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "senac-ni",
    type: "public_body",
    name: "SENAC Northern Ireland",
    url: "https://senac.co.uk",
    description: "Free, independent advice and advocacy for families in Northern Ireland navigating the SEN system.",
    category: "Legal, advice and advocacy organisations",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "contact-ni",
    type: "public_body",
    name: "Contact — Northern Ireland",
    url: "https://contact.org.uk/northernireland",
    description: "Information and advice for families with disabled children in Northern Ireland.",
    category: "Legal, advice and advocacy organisations",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
  {
    id: "niccy-too-little-too-late",
    type: "sector_briefing",
    name: "NICCY Too Little Too Late review 2020",
    url: "https://www.niccy.org/education-inequalities/special-educational-needs-sen",
    description: "Northern Ireland Commissioner for Children and Young People rights-based review of SEN provision documenting significant failures.",
    category: "Research, analysis and sector expertise",
    usedIn: ["/devolved-nations"],
    dateAccessed: "2026-02-19",
  },
];

// =============================================================================
// SOURCE LOOKUP FUNCTIONS
// =============================================================================

/** Get all sources used on a specific page */
export function getSourcesForPage(pagePath: string): ContentSource[] {
  return sourceRegistry.filter(source => source.usedIn.includes(pagePath));
}

/** Get a source by its ID */
export function getSourceById(id: string): ContentSource | undefined {
  return sourceRegistry.find(source => source.id === id);
}

/** Get sources by type */
export function getSourcesByType(type: AcceptedSourceType): ContentSource[] {
  return sourceRegistry.filter(source => source.type === type);
}

/** Get sources grouped by category, respecting display order */
export function getSourcesByCategory(): { category: string; sources: ContentSource[] }[] {
  const grouped = new Map<string, ContentSource[]>();

  for (const source of sourceRegistry) {
    const list = grouped.get(source.category) || [];
    list.push(source);
    grouped.set(source.category, list);
  }

  // Sort by predefined order, then alphabetically for any new categories
  return Array.from(grouped.entries())
    .sort(([a], [b]) => {
      const ai = sourceCategoryOrder.indexOf(a);
      const bi = sourceCategoryOrder.indexOf(b);
      if (ai === -1 && bi === -1) return a.localeCompare(b);
      if (ai === -1) return 1;
      if (bi === -1) return -1;
      return ai - bi;
    })
    .map(([category, sources]) => ({ category, sources }));
}

// =============================================================================
// SOURCE DISPLAY HELPERS
// =============================================================================

export const sourceTypeLabels: Record<AcceptedSourceType, string> = {
  government_primary: "Government source",
  parliamentary: "Parliamentary source",
  public_body: "Public body",
  established_media: "Media report",
  sector_briefing: "Sector briefing",
};
