/**
 * Theme Ontology — Structured neurodevelopmental modelling
 *
 * 3-layer classification: Theme → Mechanism → Context
 * All labels are plain English. No new themes may be generated by AI.
 */

// ───────────────────────────────────────────────────
// Layer 1: Themes (high-level patterns)
// ───────────────────────────────────────────────────

export const THEMES = [
  "Identity and self concept",
  "Sensory overwhelm",
  "Executive function friction",
  "Regulation and nervous system load",
  "Strength based engagement",
  "Sleep and recovery",
  "Demand and autonomy tension",
  "Social communication load",
  "Energy and recovery",
] as const;

export type ThemeKey = (typeof THEMES)[number];

export const THEME_DESCRIPTIONS: Record<ThemeKey, string> = {
  "Identity and self concept":
    "How the child sees themselves, including self-worth, sense of difference, and emerging identity.",
  "Sensory overwhelm":
    "Sensory input causing overload, avoidance, or distress across different environments.",
  "Executive function friction":
    "Difficulty with planning, starting tasks, following instructions, or managing time.",
  "Regulation and nervous system load":
    "Patterns of dysregulation, meltdowns, shutdowns, and the nervous system operating under load.",
  "Strength based engagement":
    "Areas where the child thrives, shows deep focus, and is intrinsically motivated.",
  "Sleep and recovery":
    "Sleep difficulties, recovery patterns, and how rest affects daytime capacity.",
  "Demand and autonomy tension":
    "Responses to demands, expectations, and authority — including avoidance and need for control.",
  "Social communication load":
    "The effort required to navigate social situations, read cues, and express needs.",
  "Energy and recovery":
    "How energy is spent and replenished across the day, including post-school crash patterns.",
};

// ───────────────────────────────────────────────────
// Layer 2: Mechanisms (underlying processes)
// ───────────────────────────────────────────────────

export const MECHANISMS = [
  "Nervous system dysregulation",
  "Sensory processing differences",
  "Dopamine motivation regulation",
  "Executive function gap",
  "Masking load",
  "Sleep disruption",
  "Trauma or chronic stress",
  "Social cognitive load",
  "Demand pressure response",
] as const;

export type MechanismKey = (typeof MECHANISMS)[number];

// ───────────────────────────────────────────────────
// Layer 3: Context tags (environments/situations)
// ───────────────────────────────────────────────────

export const CONTEXT_TAGS = [
  "Home",
  "School",
  "Clubs",
  "Crowds",
  "Transitions",
  "Authority interaction",
  "Peer groups",
  "Morning",
  "After school",
  "Evening",
  "Busy environments",
] as const;

export type ContextTag = (typeof CONTEXT_TAGS)[number];

// ───────────────────────────────────────────────────
// Signal → Mechanism mapping
// ───────────────────────────────────────────────────

/** Maps signal domain → which mechanisms are most likely involved */
export const DOMAIN_MECHANISM_MAP: Record<string, MechanismKey[]> = {
  Environment: ["Sensory processing differences", "Nervous system dysregulation"],
  "Nervous System": ["Nervous system dysregulation", "Trauma or chronic stress"],
  Sensory: ["Sensory processing differences", "Nervous system dysregulation"],
  "Executive Function": ["Executive function gap", "Dopamine motivation regulation"],
  Masking: ["Masking load", "Nervous system dysregulation", "Social cognitive load"],
  Communication: ["Social cognitive load", "Executive function gap"],
  Behaviour: ["Nervous system dysregulation", "Demand pressure response", "Trauma or chronic stress"],
  Strengths: ["Dopamine motivation regulation"],
  "Energy and Recovery": ["Nervous system dysregulation", "Masking load", "Sleep disruption"],
};

// ───────────────────────────────────────────────────
// Mechanism → Theme mapping
// ───────────────────────────────────────────────────

export const MECHANISM_THEME_MAP: Record<MechanismKey, ThemeKey[]> = {
  "Nervous system dysregulation": ["Regulation and nervous system load", "Energy and recovery"],
  "Sensory processing differences": ["Sensory overwhelm"],
  "Dopamine motivation regulation": ["Strength based engagement", "Executive function friction"],
  "Executive function gap": ["Executive function friction"],
  "Masking load": ["Energy and recovery", "Identity and self concept"],
  "Sleep disruption": ["Sleep and recovery", "Energy and recovery"],
  "Trauma or chronic stress": ["Regulation and nervous system load", "Identity and self concept"],
  "Social cognitive load": ["Social communication load"],
  "Demand pressure response": ["Demand and autonomy tension"],
};

// ───────────────────────────────────────────────────
// Signal keyword → Context tag inference
// ───────────────────────────────────────────────────

export const CONTEXT_KEYWORDS: Record<ContextTag, string[]> = {
  Home: ["home", "house", "bedroom", "family", "parent", "mum", "dad"],
  School: ["school", "classroom", "teacher", "lesson", "assembly", "playground"],
  Clubs: ["club", "activity", "after-school club", "sport", "swimming", "brownies", "scouts"],
  Crowds: ["crowd", "busy", "noisy", "supermarket", "shopping", "party", "event"],
  Transitions: ["transition", "change", "moving", "switch", "new", "different"],
  "Authority interaction": ["teacher", "adult", "told to", "authority", "instruction", "demand"],
  "Peer groups": ["friend", "peer", "other children", "social", "group", "playground"],
  Morning: ["morning", "getting ready", "wake", "breakfast", "before school"],
  "After school": ["after school", "pick up", "home time", "3pm", "after-school"],
  Evening: ["evening", "bedtime", "night", "dinner", "bath"],
  "Busy environments": ["busy", "noisy", "crowded", "overwhelming", "too much"],
};

// ───────────────────────────────────────────────────
// Known repeating patterns
// ───────────────────────────────────────────────────

export interface KnownPattern {
  id: string;
  label: string;
  description: string;
  /** Mechanisms that must be present */
  requiredMechanisms: MechanismKey[];
  /** Contexts that strengthen the match */
  boostContexts: ContextTag[];
  /** Minimum signal count to trigger */
  minSignals: number;
}

export const KNOWN_PATTERNS: KnownPattern[] = [
  {
    id: "after-school-crash",
    label: "After school crash",
    description: "A pattern of holding it together at school followed by collapse at home — often driven by masking load and nervous system depletion.",
    requiredMechanisms: ["Masking load", "Nervous system dysregulation"],
    boostContexts: ["School", "After school", "Home"],
    minSignals: 3,
  },
  {
    id: "demand-escalation",
    label: "Demand escalation",
    description: "Demands or expectations trigger escalating resistance or distress — often linked to autonomy needs or demand pressure responses.",
    requiredMechanisms: ["Demand pressure response"],
    boostContexts: ["School", "Authority interaction", "Morning"],
    minSignals: 2,
  },
  {
    id: "sensory-overload",
    label: "Sensory overload",
    description: "Sensory input accumulates past a threshold, causing shutdown or meltdown — especially in busy or unpredictable environments.",
    requiredMechanisms: ["Sensory processing differences"],
    boostContexts: ["Busy environments", "Crowds", "School"],
    minSignals: 2,
  },
  {
    id: "transition-stress",
    label: "Transition stress",
    description: "Moving between activities, environments, or expectations causes significant distress or refusal.",
    requiredMechanisms: ["Executive function gap", "Nervous system dysregulation"],
    boostContexts: ["Transitions", "School", "Morning"],
    minSignals: 2,
  },
  {
    id: "interest-driven-engagement",
    label: "Interest driven engagement",
    description: "The child shows exceptional focus, energy, and capability when engaged with topics or activities that genuinely interest them.",
    requiredMechanisms: ["Dopamine motivation regulation"],
    boostContexts: ["Home", "Clubs"],
    minSignals: 2,
  },
];

// ───────────────────────────────────────────────────
// Confidence labels
// ───────────────────────────────────────────────────

export type ThemeConfidence = "emerging" | "developing" | "established";

export const CONFIDENCE_THRESHOLDS = {
  emerging: 2,     // 2-3 signals
  developing: 4,   // 4-5 signals
  established: 6,  // 6+ signals
} as const;

export function getThemeConfidence(signalCount: number): ThemeConfidence {
  if (signalCount >= CONFIDENCE_THRESHOLDS.established) return "established";
  if (signalCount >= CONFIDENCE_THRESHOLDS.developing) return "developing";
  return "emerging";
}
